global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # Monitoramento do Otel Collector (métricas do container Otel)
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          hostname: 'odin-lab'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.*"
        replacement: "$1"  # Seta só o IP no instance

  # Monitoramento do Host via Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          hostname: 'odin-lab'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.*"
        replacement: "$1"  # Mesmo esquema: IP puro no instance
